sudo: required
dist: xenial

stages:
  - build
  - docs
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      language: cpp
      before_install:
      - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
      - sudo apt-get update -qq
      - sudo apt-get install --yes qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
      - sudo apt-get install --yes qt5-default qttools5-dev-tools
      script:
      - qmake -project
      - qmake src/FrogArchiver.pro
      - make
    - stage: docs
      language: node_js
      node_js:
      - "10"
      before_install:
      - yarn install
      script:
      - yarn docs:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        committer-from-gh: true
        local-dir: docs/.vuepress/dist
        on:
          branch: master
