sudo: required
dist: xenial
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt571-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt571[QTPACKAGE]

script:
  - source /opt/qt571/bin/qt571-env.sh
  - /opt/qt571/bin/qmake -project
  - /opt/qt571/bin/qmake src/FrogArchiver.pro
  - make
